[package]
name = "luna_ast"
description = "Structures for the Lua syntax tree."
authors = ["Kyle Guarco <kyleguarco55@gmail.com>"]
version = "5.4.4"
edition = "2021"
license-file = "LICENSE.txt"

[lib]

[dependencies]
