[package]
name = "luna_parser"
description = "A parser for the Lua programming language"
version.workspace = true
authors.workspace = true
edition.workspace = true
license-file.workspace = true

[lib]

[dependencies]
nom = "7.1.3"
luna_ast = { path = "../luna_ast" }
