[package]
name = "luna_parser"
description = "A parser for the Lua programming language."
authors = ["Kyle Guarco <kyleguarco55@gmail.com>"]
version = "5.4.4"
edition = "2021"
license-file = "LICENSE.txt"

[lib]

[dependencies]
nom = "7.1.3"
luna_ast = { path = "../luna_ast" }
