use std::fmt::Debug;

use crate::cn;

use super::mode::{FormatKind, OpMode};

// From `lopcodes.h`:
/*===========================================================================
  We assume that instructions are unsigned 32-bit integers.
  All instructions have an opcode in the first 7 bits.
  Instructions can have the following formats:

		3 3 2 2 2 2 2 2 2 2 2 2 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0
		1 0 9 8 7 6 5 4 3 2 1 0 9 8 7 6 5 4 3 2 1 0 9 8 7 6 5 4 3 2 1 0
iABC          C(8)     |      B(8)     |k|     A(8)      |   Op(7)     |
iABx                Bx(17)               |     A(8)      |   Op(7)     |
iAsBx              sBx (signed)(17)      |     A(8)      |   Op(7)     |
iAx                           Ax(25)                     |   Op(7)     |
isJ                           sJ (signed)(25)            |   Op(7)     |

  A signed argument is represented in excess K: the represented value is
  the written unsigned value minus K, where K is half the maximum for the
  corresponding unsigned argument.
===========================================================================*/

/// An alias for the unsigned byte `u8` that represents a value for one of
/// the 83 possible Lua opcodes.
pub type OpCodeId = u8;

#[repr(u8)]
#[derive(Debug, Clone, Copy)]
pub enum OpCode {
	Move = cn::OP_MOVE,
	LoadI = cn::OP_LOADI,
	LoadF = cn::OP_LOADF,
	LoadK = cn::OP_LOADK,
	LoadKX = cn::OP_LOADKX,
	LoadFalse = cn::OP_LOADFALSE,
	LFalseSkip = cn::OP_LFALSESKIP,
	LoadTrue = cn::OP_LOADTRUE,
	LoadNil = cn::OP_LOADNIL,
	GetUpval = cn::OP_GETUPVAL,
	SetUpval = cn::OP_SETUPVAL,
	GetTabUp = cn::OP_GETTABUP,
	GetTable = cn::OP_GETTABLE,
	GetI = cn::OP_GETI,
	GetField = cn::OP_GETFIELD,
	SetTabUp = cn::OP_SETTABUP,
	SetTable = cn::OP_SETTABLE,
	SetI = cn::OP_SETI,
	SetField = cn::OP_SETFIELD,
	NewTable = cn::OP_NEWTABLE,
	ISelf = cn::OP_ISELF,
	AddI = cn::OP_ADDI,
	AddK = cn::OP_ADDK,
	SubK = cn::OP_SUBK,
	MulK = cn::OP_MULK,
	ModK = cn::OP_MODK,
	PowK = cn::OP_POWK,
	DivK = cn::OP_DIVK,
	IDivK = cn::OP_IDIVK,
	BAndK = cn::OP_BANDK,
	BOrK = cn::OP_BORK,
	BXorK = cn::OP_BXORK,
	ShrI = cn::OP_SHRI,
	ShlI = cn::OP_SHLI,
	Add = cn::OP_ADD,
	Sub = cn::OP_SUB,
	Mul = cn::OP_MUL,
	Mod = cn::OP_MOD,
	Pow = cn::OP_POW,
	Div = cn::OP_DIV,
	IDiv = cn::OP_IDIV,
	BAnd = cn::OP_BAND,
	BOr = cn::OP_BOR,
	BXor = cn::OP_BXOR,
	Shl = cn::OP_SHL,
	Shr = cn::OP_SHR,
	MMBin = cn::OP_MMBIN,
	MMBinI = cn::OP_MMBINI,
	MMBinK = cn::OP_MMBINK,
	UnM = cn::OP_UNM,
	BNot = cn::OP_BNOT,
	Not = cn::OP_NOT,
	Len = cn::OP_LEN,
	Concat = cn::OP_CONCAT,
	Close = cn::OP_CLOSE,
	Tbc = cn::OP_TBC,
	Jmp = cn::OP_JMP,
	Eq = cn::OP_EQ,
	Lt = cn::OP_LT,
	Le = cn::OP_LE,
	EqK = cn::OP_EQK,
	EqI = cn::OP_EQI,
	LtI = cn::OP_LTI,
	LeI = cn::OP_LEI,
	GtI = cn::OP_GTI,
	GeI = cn::OP_GEI,
	Test = cn::OP_TEST,
	TestSet = cn::OP_TESTSET,
	Call = cn::OP_CALL,
	TailCall = cn::OP_TAILCALL,
	Return = cn::OP_RETURN,
	Return0 = cn::OP_RETURN0,
	Return1 = cn::OP_RETURN1,
	ForLoop = cn::OP_FORLOOP,
	ForPrep = cn::OP_FORPREP,
	TForPrep = cn::OP_TFORPREP,
	TForCall = cn::OP_TFORCALL,
	TForLoop = cn::OP_TFORLOOP,
	SetList = cn::OP_SETLIST,
	Closure = cn::OP_CLOSURE,
	VarArg = cn::OP_VARARG,
	VarArgPrep = cn::OP_VARARGPREP,
	ExtraArg = cn::OP_EXTRAARG,
}

impl TryFrom<OpCodeId> for OpCode {
	type Error = ();

	fn try_from(value: OpCodeId) -> Result<Self, Self::Error> {
		Self::from_opcodeid(value).ok_or(())
	}
}

impl OpCode {
	pub fn from_opcodeid(code: OpCodeId) -> Option<Self> {
		match code {
			cn::OP_MOVE => Some(Self::Move),
			cn::OP_LOADI => Some(Self::LoadI),
			cn::OP_LOADF => Some(Self::LoadF),
			cn::OP_LOADK => Some(Self::LoadK),
			cn::OP_LOADKX => Some(Self::LoadKX),
			cn::OP_LOADFALSE => Some(Self::LoadFalse),
			cn::OP_LFALSESKIP => Some(Self::LFalseSkip),
			cn::OP_LOADTRUE => Some(Self::LoadTrue),
			cn::OP_LOADNIL => Some(Self::LoadNil),
			cn::OP_GETUPVAL => Some(Self::GetUpval),
			cn::OP_SETUPVAL => Some(Self::SetUpval),
			cn::OP_GETTABUP => Some(Self::GetTabUp),
			cn::OP_GETTABLE => Some(Self::GetTable),
			cn::OP_GETI => Some(Self::GetI),
			cn::OP_GETFIELD => Some(Self::GetField),
			cn::OP_SETTABUP => Some(Self::SetTabUp),
			cn::OP_SETTABLE => Some(Self::SetTable),
			cn::OP_SETI => Some(Self::SetI),
			cn::OP_SETFIELD => Some(Self::SetField),
			cn::OP_NEWTABLE => Some(Self::NewTable),
			cn::OP_ISELF => Some(Self::ISelf),
			cn::OP_ADDI => Some(Self::AddI),
			cn::OP_ADDK => Some(Self::AddK),
			cn::OP_SUBK => Some(Self::SubK),
			cn::OP_MULK => Some(Self::MulK),
			cn::OP_MODK => Some(Self::ModK),
			cn::OP_POWK => Some(Self::PowK),
			cn::OP_DIVK => Some(Self::DivK),
			cn::OP_IDIVK => Some(Self::IDivK),
			cn::OP_BANDK => Some(Self::BAndK),
			cn::OP_BORK => Some(Self::BOrK),
			cn::OP_BXORK => Some(Self::BXorK),
			cn::OP_SHRI => Some(Self::ShrI),
			cn::OP_SHLI => Some(Self::ShlI),
			cn::OP_ADD => Some(Self::Add),
			cn::OP_SUB => Some(Self::Sub),
			cn::OP_MUL => Some(Self::Mul),
			cn::OP_MOD => Some(Self::Mod),
			cn::OP_POW => Some(Self::Pow),
			cn::OP_DIV => Some(Self::Div),
			cn::OP_IDIV => Some(Self::IDiv),
			cn::OP_BAND => Some(Self::BAnd),
			cn::OP_BOR => Some(Self::BOr),
			cn::OP_BXOR => Some(Self::BXor),
			cn::OP_SHL => Some(Self::Shl),
			cn::OP_SHR => Some(Self::Shr),
			cn::OP_MMBIN => Some(Self::MMBin),
			cn::OP_MMBINI => Some(Self::MMBinI),
			cn::OP_MMBINK => Some(Self::MMBinK),
			cn::OP_UNM => Some(Self::UnM),
			cn::OP_BNOT => Some(Self::BNot),
			cn::OP_NOT => Some(Self::Not),
			cn::OP_LEN => Some(Self::Len),
			cn::OP_CONCAT => Some(Self::Concat),
			cn::OP_CLOSE => Some(Self::Close),
			cn::OP_TBC => Some(Self::Tbc),
			cn::OP_JMP => Some(Self::Jmp),
			cn::OP_EQ => Some(Self::Eq),
			cn::OP_LT => Some(Self::Lt),
			cn::OP_LE => Some(Self::Le),
			cn::OP_EQK => Some(Self::EqK),
			cn::OP_EQI => Some(Self::EqI),
			cn::OP_LTI => Some(Self::LtI),
			cn::OP_LEI => Some(Self::LeI),
			cn::OP_GTI => Some(Self::GtI),
			cn::OP_GEI => Some(Self::GeI),
			cn::OP_TEST => Some(Self::Test),
			cn::OP_TESTSET => Some(Self::TestSet),
			cn::OP_CALL => Some(Self::Call),
			cn::OP_TAILCALL => Some(Self::TailCall),
			cn::OP_RETURN => Some(Self::Return),
			cn::OP_RETURN0 => Some(Self::Return0),
			cn::OP_RETURN1 => Some(Self::Return1),
			cn::OP_FORLOOP => Some(Self::ForLoop),
			cn::OP_FORPREP => Some(Self::ForPrep),
			cn::OP_TFORPREP => Some(Self::TForPrep),
			cn::OP_TFORCALL => Some(Self::TForCall),
			cn::OP_TFORLOOP => Some(Self::TForLoop),
			cn::OP_SETLIST => Some(Self::SetList),
			cn::OP_CLOSURE => Some(Self::Closure),
			cn::OP_VARARG => Some(Self::VarArg),
			cn::OP_VARARGPREP => Some(Self::VarArgPrep),
			cn::OP_EXTRAARG => Some(Self::ExtraArg),
			_ => None,
		}
	}

	pub fn name(self) -> &'static str {
		match self {
			Self::Move => "MOVE",
			Self::LoadI => "LOADI",
			Self::LoadF => "LOADF",
			Self::LoadK => "LOADK",
			Self::LoadKX => "LOADKX",
			Self::LoadFalse => "LOADFALSE",
			Self::LFalseSkip => "LFALSESKIP",
			Self::LoadTrue => "LOADTRUE",
			Self::LoadNil => "LOADNIL",
			Self::GetUpval => "GETUPVAL",
			Self::SetUpval => "SETUPVAL",
			Self::GetTabUp => "GETTABUP",
			Self::GetTable => "GETTABLE",
			Self::GetI => "GETI",
			Self::GetField => "GETFIELD",
			Self::SetTabUp => "SETTABUP",
			Self::SetTable => "SETTABLE",
			Self::SetI => "SETI",
			Self::SetField => "SETFIELD",
			Self::NewTable => "NEWTABLE",
			Self::ISelf => "SELF",
			Self::AddI => "ADDI",
			Self::AddK => "ADDK",
			Self::SubK => "SUBK",
			Self::MulK => "MULK",
			Self::ModK => "MODK",
			Self::PowK => "POWK",
			Self::DivK => "DIVK",
			Self::IDivK => "IDIVK",
			Self::BAndK => "BANDK",
			Self::BOrK => "BORK",
			Self::BXorK => "BXORK",
			Self::ShrI => "SHRI",
			Self::ShlI => "SHLI",
			Self::Add => "ADD",
			Self::Sub => "SUB",
			Self::Mul => "MUL",
			Self::Mod => "MOD",
			Self::Pow => "POW",
			Self::Div => "DIV",
			Self::IDiv => "IDIV",
			Self::BAnd => "BAND",
			Self::BOr => "BOR",
			Self::BXor => "BXOR",
			Self::Shl => "SHL",
			Self::Shr => "SHR",
			Self::MMBin => "MMBIN",
			Self::MMBinI => "MMBINI",
			Self::MMBinK => "MMBINK",
			Self::UnM => "UNM",
			Self::BNot => "BNOT",
			Self::Not => "NOT",
			Self::Len => "LEN",
			Self::Concat => "CONCAT",
			Self::Close => "CLOSE",
			Self::Tbc => "TBC",
			Self::Jmp => "JMP",
			Self::Eq => "EQ",
			Self::Lt => "LT",
			Self::Le => "LE",
			Self::EqK => "EQK",
			Self::EqI => "EQI",
			Self::LtI => "LTI",
			Self::LeI => "LEI",
			Self::GtI => "GTI",
			Self::GeI => "GEI",
			Self::Test => "TEST",
			Self::TestSet => "TESTSET",
			Self::Call => "CALL",
			Self::TailCall => "TAILCALL",
			Self::Return => "RETURN",
			Self::Return0 => "RETURN0",
			Self::Return1 => "RETURN1",
			Self::ForLoop => "FORLOOP",
			Self::ForPrep => "FORPREP",
			Self::TForPrep => "TFORPREP",
			Self::TForCall => "TFORCALL",
			Self::TForLoop => "TFORLOOP",
			Self::SetList => "SETLIST",
			Self::Closure => "CLOSURE",
			Self::VarArg => "VARARG",
			Self::VarArgPrep => "VARARGPREP",
			Self::ExtraArg => "EXTRAARG",
		}
	}

	pub const fn mode(self) -> OpMode {
		match self {
			Self::Move => OpMode::new(false, false, false, false, true, FormatKind::ABC),
			Self::LoadI => OpMode::new(false, false, false, false, true, FormatKind::ASBX),
			Self::LoadF => OpMode::new(false, false, false, false, true, FormatKind::ASBX),
			Self::LoadK => OpMode::new(false, false, false, false, true, FormatKind::ABX),
			Self::LoadKX => OpMode::new(false, false, false, false, true, FormatKind::ABX),
			Self::LoadFalse => OpMode::new(false, false, false, false, true, FormatKind::ABC),
			Self::LFalseSkip => OpMode::new(false, false, false, false, true, FormatKind::ABC),
			Self::LoadTrue => OpMode::new(false, false, false, false, true, FormatKind::ABC),
			Self::LoadNil => OpMode::new(false, false, false, false, true, FormatKind::ABC),
			Self::GetUpval => OpMode::new(false, false, false, false, true, FormatKind::ABC),
			Self::SetUpval => OpMode::new(false, false, false, false, false, FormatKind::ABC),
			Self::GetTabUp => OpMode::new(false, false, false, false, true, FormatKind::ABC),
			Self::GetTable => OpMode::new(false, false, false, false, true, FormatKind::ABC),
			Self::GetI => OpMode::new(false, false, false, false, true, FormatKind::ABC),
			Self::GetField => OpMode::new(false, false, false, false, true, FormatKind::ABC),
			Self::SetTabUp => OpMode::new(false, false, false, false, false, FormatKind::ABC),
			Self::SetTable => OpMode::new(false, false, false, false, false, FormatKind::ABC),
			Self::SetI => OpMode::new(false, false, false, false, false, FormatKind::ABC),
			Self::SetField => OpMode::new(false, false, false, false, false, FormatKind::ABC),
			Self::NewTable => OpMode::new(false, false, false, false, true, FormatKind::ABC),
			Self::ISelf => OpMode::new(false, false, false, false, true, FormatKind::ABC),
			Self::AddI => OpMode::new(false, false, false, false, true, FormatKind::ABC),
			Self::AddK => OpMode::new(false, false, false, false, true, FormatKind::ABC),
			Self::SubK => OpMode::new(false, false, false, false, true, FormatKind::ABC),
			Self::MulK => OpMode::new(false, false, false, false, true, FormatKind::ABC),
			Self::ModK => OpMode::new(false, false, false, false, true, FormatKind::ABC),
			Self::PowK => OpMode::new(false, false, false, false, true, FormatKind::ABC),
			Self::DivK => OpMode::new(false, false, false, false, true, FormatKind::ABC),
			Self::IDivK => OpMode::new(false, false, false, false, true, FormatKind::ABC),
			Self::BAndK => OpMode::new(false, false, false, false, true, FormatKind::ABC),
			Self::BOrK => OpMode::new(false, false, false, false, true, FormatKind::ABC),
			Self::BXorK => OpMode::new(false, false, false, false, true, FormatKind::ABC),
			Self::ShrI => OpMode::new(false, false, false, false, true, FormatKind::ABC),
			Self::ShlI => OpMode::new(false, false, false, false, true, FormatKind::ABC),
			Self::Add => OpMode::new(false, false, false, false, true, FormatKind::ABC),
			Self::Sub => OpMode::new(false, false, false, false, true, FormatKind::ABC),
			Self::Mul => OpMode::new(false, false, false, false, true, FormatKind::ABC),
			Self::Mod => OpMode::new(false, false, false, false, true, FormatKind::ABC),
			Self::Pow => OpMode::new(false, false, false, false, true, FormatKind::ABC),
			Self::Div => OpMode::new(false, false, false, false, true, FormatKind::ABC),
			Self::IDiv => OpMode::new(false, false, false, false, true, FormatKind::ABC),
			Self::BAnd => OpMode::new(false, false, false, false, true, FormatKind::ABC),
			Self::BOr => OpMode::new(false, false, false, false, true, FormatKind::ABC),
			Self::BXor => OpMode::new(false, false, false, false, true, FormatKind::ABC),
			Self::Shl => OpMode::new(false, false, false, false, true, FormatKind::ABC),
			Self::Shr => OpMode::new(false, false, false, false, true, FormatKind::ABC),
			Self::MMBin => OpMode::new(true, false, false, false, false, FormatKind::ABC),
			Self::MMBinI => OpMode::new(true, false, false, false, false, FormatKind::ABC),
			Self::MMBinK => OpMode::new(true, false, false, false, false, FormatKind::ABC),
			Self::UnM => OpMode::new(false, false, false, false, true, FormatKind::ABC),
			Self::BNot => OpMode::new(false, false, false, false, true, FormatKind::ABC),
			Self::Not => OpMode::new(false, false, false, false, true, FormatKind::ABC),
			Self::Len => OpMode::new(false, false, false, false, true, FormatKind::ABC),
			Self::Concat => OpMode::new(false, false, false, false, true, FormatKind::ABC),
			Self::Close => OpMode::new(false, false, false, false, false, FormatKind::ABC),
			Self::Tbc => OpMode::new(false, false, false, false, false, FormatKind::ABC),
			Self::Jmp => OpMode::new(false, false, false, false, false, FormatKind::ISJ),
			Self::Eq => OpMode::new(false, false, false, true, false, FormatKind::ABC),
			Self::Lt => OpMode::new(false, false, false, true, false, FormatKind::ABC),
			Self::Le => OpMode::new(false, false, false, true, false, FormatKind::ABC),
			Self::EqK => OpMode::new(false, false, false, true, false, FormatKind::ABC),
			Self::EqI => OpMode::new(false, false, false, true, false, FormatKind::ABC),
			Self::LtI => OpMode::new(false, false, false, true, false, FormatKind::ABC),
			Self::LeI => OpMode::new(false, false, false, true, false, FormatKind::ABC),
			Self::GtI => OpMode::new(false, false, false, true, false, FormatKind::ABC),
			Self::GeI => OpMode::new(false, false, false, true, false, FormatKind::ABC),
			Self::Test => OpMode::new(false, false, false, true, false, FormatKind::ABC),
			Self::TestSet => OpMode::new(false, false, false, true, true, FormatKind::ABC),
			Self::Call => OpMode::new(false, true, true, false, true, FormatKind::ABC),
			Self::TailCall => OpMode::new(false, true, true, false, true, FormatKind::ABC),
			Self::Return => OpMode::new(false, false, true, false, false, FormatKind::ABC),
			Self::Return0 => OpMode::new(false, false, false, false, false, FormatKind::ABC),
			Self::Return1 => OpMode::new(false, false, false, false, false, FormatKind::ABC),
			Self::ForLoop => OpMode::new(false, false, false, false, true, FormatKind::ABX),
			Self::ForPrep => OpMode::new(false, false, false, false, true, FormatKind::ABX),
			Self::TForPrep => OpMode::new(false, false, false, false, false, FormatKind::ABX),
			Self::TForCall => OpMode::new(false, false, false, false, false, FormatKind::ABC),
			Self::TForLoop => OpMode::new(false, false, false, false, true, FormatKind::ABX),
			Self::SetList => OpMode::new(false, false, true, false, false, FormatKind::ABC),
			Self::Closure => OpMode::new(false, false, false, false, true, FormatKind::ABX),
			Self::VarArg => OpMode::new(false, true, false, false, true, FormatKind::ABC),
			Self::VarArgPrep => OpMode::new(false, false, true, false, true, FormatKind::ABC),
			Self::ExtraArg => OpMode::new(false, false, false, false, false, FormatKind::AX),
		}
	}
}
