use core::str::FromStr;

pub enum Reserved {
    And,
    Break,
    Do,
    Else,
    ElseIf,
    End,
    False,
    For,
    Function,
    Goto,
    If,
    In,
    Local,
    Nil,
    Not,
    Or,
    Repeat,
    Return,
    Then,
    True,
    Until,
    While,
    FloorDiv,
    Concat,
    Dots,
    Equal,
    GreaterEqual,
    LessEqual,
    NotEqual,
    ShiftLeft,
    ShiftRight,
    DoubleColon,
    EndOfScript,
    Float,
    Integer,
    Name,
    String,
}

impl FromStr for Reserved {
    type Err = ();

    fn from_str(token: &str) -> Result<Self, Self::Err> {
        match token {
            "and" => Ok(Self::And),
            "break" => Ok(Self::Break),
            "do" => Ok(Self::Do),
            "else" => Ok(Self::Else),
            "elseif" => Ok(Self::ElseIf),
            "end" => Ok(Self::End),
            "false" => Ok(Self::False),
            "for" => Ok(Self::For),
            "function" => Ok(Self::Function),
            "goto" => Ok(Self::Goto),
            "if" => Ok(Self::If),
            "in" => Ok(Self::In),
            "local" => Ok(Self::Local),
            "nil" => Ok(Self::Nil),
            "not" => Ok(Self::Not),
            "or" => Ok(Self::Or),
            "repeat" => Ok(Self::Repeat),
            "return" => Ok(Self::Return),
            "then" => Ok(Self::Then),
            "true" => Ok(Self::True),
            "until" => Ok(Self::Until),
            "while" => Ok(Self::While),
            "//" => Ok(Self::FloorDiv),
            ".." => Ok(Self::Concat),
            "..." => Ok(Self::Dots),
            "==" => Ok(Self::Equal),
            ">=" => Ok(Self::GreaterEqual),
            "<=" => Ok(Self::LessEqual),
            "~=" => Ok(Self::NotEqual),
            "<<" => Ok(Self::ShiftLeft),
            ">>" => Ok(Self::ShiftRight),
            "::" => Ok(Self::DoubleColon),
            "<eof>" => Ok(Self::EndOfScript),
            "<number>" => Ok(Self::Float),
            "<integer>" => Ok(Self::Integer),
            "<name>" => Ok(Self::Name),
            "<string>" => Ok(Self::String),
            _ => Err(()),
        }
    }
}
