[package]
name = "luna"
description = "The Lua programming language, in Rust."
authors = ["Kyle Guarco <kyleguarco55@gmail.com>"]
version = "5.4.4"
edition = "2021"
license-file = "LICENSE.txt"

[dependencies]
luna_parser = { path = "../luna_parser" }
